// src/components/SearchBar.jsx
import Form from 'react-bootstrap/Form';

const SearchBar = ({ value, visible, onChange }) => {
  if (!visible) {
    return null;
  }
  return (
    <>
      <Form.Label htmlFor="searchBar">Search Question</Form.Label>
      <Form.Control
        value={value}
        type="text"
        id="searchBar"
        className="mb-5"
        onChange={onChange}
      />
    </>
  );
};

export default SearchBar;

// src/components/Searchbar.vue
<script setup>
const searchTerm = defineModel()
</script>
<template>
  <div class="mt-3">
    <input v-model="searchTerm" type="text" id="searchTerm" name="searchTerm" class="form-control" placeholder="Search for Questions"/>
    <label hidden for="searchTerm">Search for Questions</label>
  </div>
</template>
<style scoped></style>
